pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch: # Habilita el botón "Run workflow"

jobs:
  tag:
    # Se ejecuta si el PR se mergeó O si se activó manualmente
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate and Push Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Buscar el último tag, si no hay ninguno usar v0.0.0
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          
          # Limpiar la 'v' si existe y separar los números
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
          # Incrementar el parche (el tercer número)
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$NEW_PATCH"

          echo "El tag anterior era: $LATEST_TAG"
          echo "Creando nueva etiqueta: $NEW_TAG"
          
          git tag $NEW_TAG
          git push origin $NEW_TAG
